### ISSUE TITLE
Newsletter form on main website fails with no visual error/warning due to Firefox content blocking

### ISSUE THREAD

**Issue by greenstatic** [planet-lia/planet-lia#51]
When subscribing to the newsletter on the main page, if the user's browser has content blocking enabled for trackers the subscription form breaks and gives the user no visual feedback something is wrong.

Error in console:
<img width="1391" alt="console error" src="https://user-images.githubusercontent.com/14580434/65528457-b6192b00-def4-11e9-8309-a6dcea6aff62.png">

Although I have custom preferences for content blocking, Firefox has enabled Enhanced Tracking Protection [on by default](https://blog.mozilla.org/blog/2019/06/04/firefox-now-available-with-enhanced-tracking-protection-by-default/) in new versions of Firefox. Therefore this could become an issue down the road.

## Expected Behavior/Solution

Detect if content blocking is enabled (the HTTP request fails); display a warning, disable submission button and maybe instructions on how to add it to the exception list. 

## Current Behavior

The user receives no visual indication something is wrong, the form does nothing after clicking on subscribe. 

## Your Environment

Firefox macOS 69.0 (custom content blocking preferences with trackers and cookies blocked)

**Comment by svigelj** [comment]
@greenstatic interesting, it works for me on Firefox (KDE Neon) 69.0.1. Any suggested fixes that wouldn't take too long to implement?

**Comment by sn3m** [comment]
Maybe try doing the POST request manually on submit event and handle the error in catch block:
```
document.forms['mc-embedded-subscribe-form'].addEventListener('submit', (event) => {
    event.preventDefault();
    // TODO do something here to show user that form is being submitted
    fetch(event.target.action, {
        method: 'POST',
        body: new URLSearchParams(new FormData(event.target)) // event.target is the form
    }).then((resp) => {
        return resp.json(); // or resp.text() or whatever the server sends
    }).then((body) => {
        // TODO handle body
    }).catch((error) => {
        // TODO handle error
    });
});
```

**Comment by greenstatic** [comment]
> @greenstatic interesting, it works for me on Firefox (KDE Neon) 69.0.1. Any suggested fixes that wouldn't take too long to implement?

They changed the default for new installations.

**Comment by greenstatic** [comment]
> Maybe try doing the POST request manually on submit event and handle the error in catch:
> 
> ```
> document.forms['mc-embedded-subscribe-form'].addEventListener('submit', (event) => {
>     event.preventDefault();
>     // TODO do something here to show user that form is being submitted
>     fetch(event.target.action, {
>         method: 'POST',
>         body: new URLSearchParams(new FormData(event.target)) // event.target is the form
>     }).then((resp) => {
>         return resp.json(); // or resp.text() or whatever the server sends
>     }).then((body) => {
>         // TODO handle body
>     }).catch((error) => {
>         // TODO handle error
>     });
> });
> ```

Any pull requests are very welcome :)

**Comment by svigelj** [comment]
When migrating placeholder page to React, I had trouble with including Mailchimp custom scripts that perform form validation. Thus I removed the custom subscription form and added Mailchimp standalone form which also solves this issue.
